------>>>>  MINOR PROJECT 


Problem statement: Create a classification model to predict whether price range of mobile based on certain specifications

Context: An entrepreneur has started his own mobile company. He wants to give tough fight to big companies like Apple, Samsung etc.
He does not know how to estimate price of mobiles his company creates. In this competitive mobile phone market, one cannot simply assume things. To solve this problem, he collects sales data of mobile phones of various companies.
He wants to find out some relation between features of a mobile phone (e.g., RAM, Internal Memory etc) and its selling price. But he is not so good at Machine Learning. So, he needs your help to solve this problem.
In this problem you do not have to predict actual price but a price range indicating how high the price is
Dataset: ‘mobile_price_range_data.csv’. Shared with this project
Details of features:

The columns are described as follows:

Dataset as 21 features and 2000 entries.
The meanings of the features are given below.


battery_power: Total energy a battery can store in one time measured in mAh
blue: Has bluetooth or not
clock_speed: speed at which microprocessor executes instructions
dual_sim: Has dual sim support or not
fc: Front Camera mega pixels
four_g: Has 4G or not
int_memory: Internal Memory in Gigabytes
m_dep: Mobile Depth in cm
mobile_wt: Weight of mobile phone
n_cores: Number of cores of processor
pc: Primary Camera mega pixels
px_height: Pixel Resolution Height
px_width: Pixel Resolution Width
ram: Random Access Memory in Mega Bytes
sc_h: Screen Height of mobile in cm
sc_w: Screen Width of mobile in cm
talk_time: longest time that a single battery charge will last when you are
three_g: Has 3G or not
touch_screen: Has touch screen or not
wifi: Has wifi or not
price_range: This is the target variable with value of 0(low cost), 1(medium cost), 2(high cost) and 3(very high cost).

Steps to consider:

Remove handle null values (if any).

Split data into training and test data.

Apply the following models on the training dataset and generate the predicted value for the test dataset
a) Logistic Regression 
b) KNN Classification
c) SVM Classifier with linear and rbf kernel

Predict the price range for test data

Compute Confusion matrix and classification report for each of these models.

Report the model with the best accuracy.


------>>>>  MODEL_1 :- LOGISTIC REGRESSION

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
mobile_dataset = pd.read_csv("D:\datascience\mobile_price_range_data.csv")
mobile_dataset.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [2]:
mobile_dataset.shape

(2000, 21)

In [3]:
mobile_dataset.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [4]:
x = mobile_dataset.iloc[:,:-1]
y = mobile_dataset.iloc[:,-1]
print(type(x))
print(type(y))


<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [5]:
x.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0

In [6]:
y.head()

0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_tr,x_ts,y_tr,y_ts = train_test_split(x,y,test_size = 0.25)
print(x_tr.shape)
print(x_ts.shape)
print(y_tr.shape)
print(y_ts.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


In [8]:
x_tr.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1341           1423     0          0.6         0  12       0          44   
742            1822     0          1.2         0   0       0           8   
98              657     0          2.5         0   0       0          37   
754            1092     0          2.7         1   8       0          45   
1597            848     1          2.8         0   1       0           8   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1341    0.8        131        5  13        501       640  2253    10     8   
742     0.2        195        6   0        172       910  2577     9     5   
98      0.7        141        2   1        476       961  1412    14     3   
754     0.8        185        1  10       1404      1424  1303    12     3   
1597    0.1        103        7   3          7      1294   436    10     6   

      talk_time  three_g  touch_screen  wifi  
1341          9        0             0     0  
742           8        1             1     0  
98           18        0             1     0  
754          20        0             1     1  
1597         15        1             1     1

In [10]:
x_ts.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
594             621     1          2.7         1   0       0          54   
1617            634     1          0.8         0   5       0          41   
796            1204     1          2.6         0   0       0          10   
566            1170     1          1.2         0   4       0          30   
992            1090     0          1.3         1   5       0          27   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
594     0.1        151        4  20        434       910  2801     6     1   
1617    0.2        192        1  12       1362      1853  3242    18    11   
796     0.3        199        7   3        480      1482  1724    11     2   
566     0.4         83        8  15         27      1722  1073     6     4   
992     0.1         91        4  16       1638      1910  1352     5     1   

      talk_time  three_g  touch_screen  wifi  
594           5        1             1     1  
1617          4        1             0     1  
796          19        1             0     0  
566           8        1             1     0  
992          11        0             1     0

In [11]:
y_tr.head()

1341    1
742     2
98      0
754     1
1597    0
Name: price_range, dtype: int64

In [13]:
y_ts.head()

594     2
1617    3
796     1
566     0
992     1
Name: price_range, dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression
m1 = LogisticRegression()
m1.fit(x_tr,y_tr)

C:\Users\arind\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
ypred = m1.predict(x_ts)
ypred

array([2, 2, 0, 1, 1, 2, 0, 3, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 3, 0, 1, 2,
       3, 0, 1, 2, 1, 1, 0, 0, 3, 0, 0, 2, 2, 3, 1, 1, 1, 3, 3, 2, 0, 3,
       0, 1, 0, 2, 0, 0, 2, 3, 0, 3, 0, 1, 0, 0, 2, 0, 1, 2, 3, 3, 3, 3,
       0, 0, 2, 3, 2, 3, 3, 2, 0, 3, 3, 0, 3, 1, 1, 2, 3, 0, 3, 2, 3, 0,
       0, 1, 3, 2, 2, 2, 0, 3, 3, 0, 2, 2, 0, 3, 0, 0, 3, 3, 0, 0, 3, 3,
       2, 2, 1, 3, 3, 0, 2, 3, 0, 3, 0, 1, 3, 2, 2, 2, 3, 3, 2, 0, 0, 0,
       3, 3, 3, 2, 3, 2, 3, 2, 2, 1, 0, 2, 1, 1, 0, 0, 0, 2, 1, 3, 0, 2,
       3, 1, 3, 1, 2, 0, 2, 1, 3, 1, 3, 3, 2, 3, 2, 1, 1, 2, 0, 3, 3, 1,
       2, 3, 0, 2, 3, 1, 3, 0, 3, 2, 2, 0, 3, 2, 1, 0, 2, 0, 0, 1, 0, 1,
       3, 0, 3, 1, 2, 0, 3, 1, 3, 0, 3, 3, 0, 1, 2, 3, 0, 3, 2, 3, 3, 0,
       1, 2, 3, 0, 0, 3, 3, 2, 0, 1, 3, 2, 3, 1, 0, 2, 1, 3, 2, 2, 0, 0,
       0, 0, 2, 3, 0, 1, 2, 2, 0, 1, 2, 0, 2, 2, 3, 2, 1, 3, 1, 2, 3, 1,
       1, 0, 2, 2, 2, 1, 0, 0, 3, 0, 3, 1, 2, 0, 2, 3, 0, 0, 2, 0, 0, 1,
       2, 0, 3, 1, 3, 1, 3, 2, 3, 3, 3, 1, 1, 2, 3,

In [16]:
from sklearn.metrics import confusion_matrix , classification_report
c_matrix = confusion_matrix(y_ts,ypred)
c_report = classification_report(y_ts,ypred)
print(c_matrix)
print(c_report)

[[107  19   1   0]
 [ 27  59  35  10]
 [  0  19  60  47]
 [  0   0  31  85]]
              precision    recall  f1-score   support

           0       0.80      0.84      0.82       127
           1       0.61      0.45      0.52       131
           2       0.47      0.48      0.47       126
           3       0.60      0.73      0.66       116

    accuracy                           0.62       500
   macro avg       0.62      0.63      0.62       500
weighted avg       0.62      0.62      0.62       500



MODEL_2 :- KNN CLASSIFICATION

In [19]:
from sklearn.neighbors import KNeighborsClassifier
m2 = KNeighborsClassifier(n_neighbors = 10)
m2.fit(x_tr,y_tr)

KNeighborsClassifier(n_neighbors=10)

In [20]:
ym2pred = m2.predict(x_ts)
ym2pred

array([2, 3, 1, 0, 1, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1,
       2, 0, 2, 2, 1, 1, 0, 0, 2, 0, 0, 2, 1, 1, 1, 1, 0, 3, 3, 2, 1, 2,
       0, 2, 0, 2, 0, 1, 2, 3, 0, 3, 0, 1, 0, 1, 1, 0, 1, 3, 3, 3, 3, 2,
       0, 1, 1, 2, 3, 2, 2, 2, 0, 3, 3, 0, 3, 0, 2, 2, 1, 1, 2, 2, 1, 0,
       0, 0, 2, 1, 1, 2, 0, 3, 3, 0, 1, 1, 1, 2, 0, 0, 2, 2, 0, 0, 3, 3,
       1, 1, 1, 3, 3, 0, 1, 1, 0, 2, 0, 1, 3, 2, 2, 3, 3, 3, 3, 0, 0, 0,
       3, 2, 3, 3, 2, 3, 3, 2, 1, 2, 0, 2, 1, 1, 0, 1, 0, 3, 0, 3, 0, 2,
       3, 2, 2, 1, 2, 0, 2, 1, 2, 1, 3, 3, 3, 3, 2, 1, 1, 2, 0, 2, 3, 0,
       1, 3, 0, 2, 3, 1, 3, 0, 2, 2, 3, 0, 1, 3, 0, 1, 3, 0, 0, 0, 0, 1,
       3, 0, 2, 1, 3, 1, 3, 1, 3, 0, 2, 2, 0, 1, 1, 3, 0, 3, 2, 1, 3, 0,
       1, 2, 3, 0, 0, 3, 3, 2, 0, 2, 3, 2, 2, 1, 0, 1, 1, 1, 2, 2, 0, 0,
       1, 0, 2, 3, 0, 1, 2, 3, 0, 1, 3, 0, 3, 1, 2, 2, 0, 3, 1, 1, 3, 1,
       1, 0, 2, 1, 1, 2, 1, 0, 3, 0, 3, 1, 1, 1, 2, 2, 1, 0, 2, 0, 0, 2,
       2, 0, 3, 2, 3, 1, 3, 3, 2, 3, 2, 1, 1, 1, 2,

In [24]:
from sklearn.metrics import confusion_matrix,classification_report
c_matrix_m2 = confusion_matrix(ym2pred,y_ts)
c_report_m2 = classification_report(ym2pred,y_ts)
print(c_matrix_m2)
print(c_report_m2)

[[124  14   0   0]
 [  3 117  10   0]
 [  0   0 108  13]
 [  0   0   8 103]]
              precision    recall  f1-score   support

           0       0.98      0.90      0.94       138
           1       0.89      0.90      0.90       130
           2       0.86      0.89      0.87       121
           3       0.89      0.93      0.91       111

    accuracy                           0.90       500
   macro avg       0.90      0.90      0.90       500
weighted avg       0.91      0.90      0.90       500



MODEL_3 :- SVM Classifier with linear and rbf kernel


In [56]:
from sklearn.svm import SVC
m1_svc = SVC(kernel='linear',C=1)
m1_svc.fit(x_tr,y_tr)

SVC(C=1, kernel='linear')

In [57]:
print('training score',m1_svc.score(x_tr,y_tr))
print('test score',m1_svc.score(x_ts,y_ts))

training score 0.9913333333333333
test score 0.964


In [58]:
ypred_svc = m1_svc.predict(x_ts)
ypred_svc

array([2, 3, 1, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 3, 0, 0, 1,
       2, 0, 2, 2, 1, 1, 0, 0, 2, 0, 0, 2, 1, 1, 1, 1, 0, 2, 3, 2, 1, 3,
       0, 2, 0, 2, 0, 1, 3, 3, 0, 3, 0, 1, 0, 1, 1, 0, 1, 2, 3, 3, 3, 2,
       0, 1, 1, 2, 3, 2, 2, 3, 0, 3, 3, 0, 3, 0, 2, 3, 1, 1, 2, 2, 1, 0,
       0, 0, 2, 1, 1, 2, 0, 3, 3, 0, 1, 1, 1, 2, 0, 0, 2, 2, 0, 0, 3, 3,
       2, 1, 1, 2, 3, 0, 1, 1, 0, 2, 0, 1, 3, 2, 2, 2, 3, 3, 3, 0, 0, 0,
       3, 3, 3, 3, 2, 2, 3, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 3, 1, 3, 0, 2,
       3, 2, 3, 1, 2, 0, 2, 1, 2, 1, 3, 3, 3, 3, 2, 1, 1, 2, 0, 2, 3, 0,
       1, 3, 0, 2, 3, 1, 3, 0, 2, 2, 2, 0, 1, 3, 0, 1, 3, 0, 0, 0, 0, 1,
       3, 0, 2, 1, 3, 1, 3, 1, 3, 0, 2, 3, 0, 1, 1, 3, 0, 3, 2, 1, 3, 0,
       1, 2, 3, 0, 0, 3, 3, 2, 0, 2, 3, 2, 2, 1, 0, 2, 1, 2, 2, 2, 0, 0,
       1, 0, 2, 3, 0, 1, 2, 3, 0, 1, 3, 0, 2, 1, 2, 2, 0, 3, 1, 1, 3, 1,
       1, 0, 2, 1, 1, 2, 1, 0, 3, 0, 3, 1, 1, 1, 2, 3, 1, 0, 2, 0, 0, 2,
       2, 0, 3, 2, 3, 1, 3, 3, 2, 3, 2, 1, 1, 2, 3,

In [59]:
from sklearn.metrics import confusion_matrix , classification_report
c_matrix_svc = confusion_matrix(ypred_svc,y_ts)
c_report_svc = classification_report(ypred_svc,y_ts)
print(c_matrix_svc)
print(c_report_svc)

[[126   4   0   0]
 [  1 125   1   0]
 [  0   2 123   8]
 [  0   0   2 108]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       130
           1       0.95      0.98      0.97       127
           2       0.98      0.92      0.95       133
           3       0.93      0.98      0.96       110

    accuracy                           0.96       500
   macro avg       0.96      0.97      0.96       500
weighted avg       0.96      0.96      0.96       500



In [42]:
m2_svc = SVC(kernel = 'rbf',gamma = 0.00000011, C = 100)
m2_svc.fit(x_tr,y_tr)

SVC(C=100, gamma=1.1e-07)

In [43]:
ypred3 = m2_svc.predict(x_ts)
ypred3

array([2, 3, 1, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 3, 0, 0, 1,
       2, 0, 2, 2, 1, 1, 0, 0, 2, 0, 0, 2, 1, 1, 1, 1, 0, 2, 3, 2, 1, 3,
       0, 2, 0, 2, 0, 1, 3, 3, 0, 3, 0, 1, 0, 1, 1, 0, 1, 2, 3, 3, 3, 2,
       0, 1, 1, 2, 3, 2, 2, 3, 0, 3, 3, 0, 3, 0, 2, 3, 1, 1, 2, 2, 1, 0,
       0, 0, 2, 2, 1, 2, 0, 3, 3, 0, 1, 1, 1, 2, 1, 0, 2, 2, 0, 0, 3, 3,
       1, 1, 1, 2, 3, 0, 1, 1, 0, 2, 0, 2, 3, 2, 2, 2, 3, 3, 3, 0, 0, 0,
       3, 3, 3, 3, 2, 3, 3, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 3, 0, 3, 0, 2,
       3, 2, 2, 1, 2, 0, 2, 1, 2, 1, 3, 3, 3, 3, 2, 1, 1, 2, 0, 2, 3, 0,
       1, 3, 0, 2, 3, 1, 3, 0, 2, 2, 3, 0, 1, 3, 0, 1, 3, 0, 0, 0, 0, 1,
       3, 0, 2, 1, 3, 1, 3, 1, 3, 0, 2, 3, 0, 1, 2, 3, 0, 3, 2, 1, 3, 0,
       1, 2, 3, 0, 0, 3, 3, 2, 0, 2, 3, 2, 2, 1, 0, 2, 1, 1, 2, 2, 0, 0,
       1, 0, 2, 3, 0, 1, 2, 3, 0, 1, 3, 0, 3, 1, 2, 2, 0, 3, 1, 1, 3, 1,
       1, 0, 2, 1, 1, 2, 1, 0, 3, 0, 3, 1, 1, 1, 2, 3, 1, 0, 2, 0, 0, 2,
       2, 0, 3, 2, 3, 1, 3, 3, 2, 3, 2, 1, 1, 2, 3,

In [45]:
from sklearn.metrics import confusion_matrix , classification_report
c_matrix_svc1 = confusion_matrix(ypred3,y_ts)
c_report_svc1 = classification_report(ypred3,y_ts)
print(c_matrix_svc1)
print(c_report_svc1)

[[127   5   0   0]
 [  0 121   5   0]
 [  0   5 118   5]
 [  0   0   3 111]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       132
           1       0.92      0.96      0.94       126
           2       0.94      0.92      0.93       128
           3       0.96      0.97      0.97       114

    accuracy                           0.95       500
   macro avg       0.95      0.95      0.95       500
weighted avg       0.95      0.95      0.95       500



---->>> Looking at all the models we can conclude that the SVM model is giving us the best accuracy  <<<-------